# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"\x1f\n\x0fGreetingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x10GreetingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2M\n\x0cGreetService\x12=\n\x08Greeting\x12\x16.greet.GreetingRequest\x1a\x17.greet.GreetingResponse\"\x00\x42\x12Z\x10grpc/greet/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\020grpc/greet/proto'
  _GREETINGREQUEST._serialized_start=22
  _GREETINGREQUEST._serialized_end=53
  _GREETINGRESPONSE._serialized_start=55
  _GREETINGRESPONSE._serialized_end=90
  _GREETSERVICE._serialized_start=92
  _GREETSERVICE._serialized_end=169
# @@protoc_insertion_point(module_scope)
