# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import greet_pb2 as greet__pb2


class GreetServiceStub(object):
    """service here refers to the method contract the client must fulfill in order to call this service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Greeting = channel.unary_unary(
                '/GreetService/Greeting',
                request_serializer=greet__pb2.GreetingRequest.SerializeToString,
                response_deserializer=greet__pb2.GreetingResponse.FromString,
                )


class GreetServiceServicer(object):
    """service here refers to the method contract the client must fulfill in order to call this service
    """

    def Greeting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Greeting': grpc.unary_unary_rpc_method_handler(
                    servicer.Greeting,
                    request_deserializer=greet__pb2.GreetingRequest.FromString,
                    response_serializer=greet__pb2.GreetingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GreetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GreetService(object):
    """service here refers to the method contract the client must fulfill in order to call this service
    """

    @staticmethod
    def Greeting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GreetService/Greeting',
            greet__pb2.GreetingRequest.SerializeToString,
            greet__pb2.GreetingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
