# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\"\x1f\n\x0fGreetingRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x10GreetingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2A\n\x0cGreetService\x12\x31\n\x08Greeting\x12\x10.GreetingRequest\x1a\x11.GreetingResponse\"\x00\x42\x19Z\x17grpc-client/proto/greetb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\027grpc-client/proto/greet'
  _GREETINGREQUEST._serialized_start=15
  _GREETINGREQUEST._serialized_end=46
  _GREETINGRESPONSE._serialized_start=48
  _GREETINGRESPONSE._serialized_end=83
  _GREETSERVICE._serialized_start=85
  _GREETSERVICE._serialized_end=150
# @@protoc_insertion_point(module_scope)
